# Generated by Django 6.0.3 on 2026-07-20 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtatStocksFlux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enregistrement', models.DateTimeField(verbose_name='Horodatage')),
                ('stock_amont_humide_t', models.FloatField(blank=True, null=True)),
                ('rythme_alimentation_moyen_th', models.FloatField(blank=True, null=True)),
                ('stock_aval_sec_t', models.FloatField(blank=True, null=True)),
                ('capacite_max_silos_t', models.FloatField(blank=True, null=True)),
                ('cadence_expedition_trains_th', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'État stocks & flux',
                'verbose_name_plural': 'États stocks & flux',
                'ordering': ['-date_enregistrement'],
            },
        ),
        migrations.CreateModel(
            name='FactJournalier',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='Journée')),
                ('journee_partielle', models.BooleanField(default=False, help_text="True si au moins une source (KPI, arrêts, procédé) n'a pas pu être ingérée pour ce jour.")),
                ('production_totale_t', models.FloatField(blank=True, null=True)),
                ('tonnage_tsm_t', models.FloatField(blank=True, help_text='Mesure distincte de production_totale_t — voir commentaire du modèle.', null=True, verbose_name='Tonnage (TSM)')),
                ('trs_calc', models.FloatField(blank=True, null=True, verbose_name='OEE')),
                ('disponibilite_globale', models.FloatField(blank=True, null=True, verbose_name='TD')),
                ('debit_th', models.FloatField(blank=True, null=True)),
                ('hm', models.FloatField(blank=True, null=True, verbose_name='Heures de marche')),
                ('a_exploitation_h', models.FloatField(blank=True, null=True)),
                ('a_externe_h', models.FloatField(blank=True, null=True)),
                ('a_maint_planifie_h', models.FloatField(blank=True, null=True)),
                ('arrets_decide_h', models.FloatField(blank=True, null=True)),
                ('a_maint_subie_h', models.FloatField(blank=True, null=True)),
                ('temps_ouverture_h', models.FloatField(blank=True, null=True)),
                ('perte_vitesse', models.FloatField(blank=True, null=True)),
                ('trg', models.FloatField(blank=True, null=True)),
                ('taux_panne', models.FloatField(blank=True, null=True)),
                ('qualite_traitee', models.CharField(blank=True, max_length=100, null=True)),
                ('conso_energie_kcalt', models.FloatField(blank=True, null=True)),
                ('cs_gaz_nm3t', models.FloatField(blank=True, null=True, verbose_name='Cs Gaz (Nm3/T)')),
                ('cs_gazoline_kgt', models.FloatField(blank=True, null=True, verbose_name='Cs Gazoline (kg/T)')),
                ('cs_fuel_kgt', models.FloatField(blank=True, null=True, verbose_name='Cs Fuel (kg/T)')),
                ('arrets_decides', models.FloatField(blank=True, null=True)),
                ('arrets_externes', models.FloatField(blank=True, null=True)),
                ('arrets_utilisation', models.FloatField(blank=True, null=True)),
                ('heures_de_marche', models.FloatField(blank=True, null=True)),
                ('heures_theoriques', models.FloatField(blank=True, null=True)),
                ('maintenance_planifiee', models.FloatField(blank=True, null=True)),
                ('arrets_oee', models.FloatField(blank=True, null=True)),
                ('pannes_maintenance', models.FloatField(blank=True, null=True)),
                ('arrets_trg', models.FloatField(blank=True, null=True)),
                ('taux_de_disponibilite', models.FloatField(blank=True, null=True)),
                ('arrets_temps_ouverture', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fait journalier',
                'verbose_name_plural': 'Faits journaliers',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FactArret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement', models.CharField(max_length=100)),
                ('nature', models.CharField(choices=[('Mécanique', 'Mécanique'), ('Electrique', 'Électrique'), ('Exploitation', 'Exploitation'), ('Installation', 'Installation'), ('Autre', 'Autre')], default='Autre', max_length=50)),
                ('type_arret', models.CharField(choices=[('Panne', 'Panne'), ('M.Planifiée', 'Maintenance planifiée'), ('M.Subie', 'Maintenance subie'), ('Utilisation', 'Utilisation / process'), ('Externe', 'Externe'), ('Décidé', 'Arrêt décidé'), ('Autre', 'Autre')], default='Autre', max_length=32)),
                ('unite', models.CharField(blank=True, default='', max_length=16)),
                ('cause_precision', models.TextField()),
                ('duree_arret_h', models.FloatField()),
                ('semaine', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mois', models.DateField(blank=True, null=True)),
                ('cle_naturelle', models.CharField(editable=False, max_length=400, unique=True)),
                ('date_evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets', to='maintenance.factjournalier', verbose_name='Journée de production')),
            ],
            options={
                'verbose_name': 'Arrêt',
                'verbose_name_plural': 'Registre des arrêts',
                'ordering': ['date_evenement', 'equipement'],
                'indexes': [models.Index(fields=['nature'], name='maintenance_nature_696970_idx'), models.Index(fields=['equipement'], name='maintenance_equipem_6ef611_idx')],
            },
        ),
    ]
