# Generated by Django 6.0.3 on 2026-07-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factjournalier',
            name='humidite_sortie_mc_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='Humidité sortie MC (%)'),
        ),
    ]
