# Generated by Django 6.0.3 on 2026-07-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_factjournalier_humidite_sortie_mc_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='factjournalier',
            name='humidite_sortie_mp_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='Humidité sortie MP (%)'),
        ),
    ]
