# Generated by Django 6.0.3 on 2026-07-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_factjournalier_humidite_sortie_mp_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifEnergetique',
            fields=[
                ('mois', models.CharField(help_text="Format YYYY-MM, ex. '2026-06'.", max_length=7, primary_key=True, serialize=False)),
                ('baseline_kcalt', models.FloatField(help_text='Cible fixée pour ce mois. Par défaut : 160 000 kcal/T.', verbose_name='Objectif de consommation (kcal/T)')),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Objectif énergétique mensuel',
                'verbose_name_plural': 'Objectifs énergétiques mensuels',
                'ordering': ['-mois'],
            },
        ),
    ]
